Adds Embedded Payment Option and fixes the module functionality for a new version of PrestaShop
Mastercard-Gateway/simplify-prestashop-module pull request #8
Opened 2021-07-27 09:16 UTC by riversy

Features:
- Add Embedded Payment Option
Fixes:
- Modal Payment Option doesn't work on the new version of PrestaShop (1.7)

2021-10-19 17:55 UTC, BlainMaguire requested changes

2021-10-19 17:55 UTC, BlainMaguire commented on views/js/simplify.embedded.js
> +            chosenPaymentOption: PAYMENT_OPTION_NEW,
Something like ```PAYMENT_OPTION_EMBEDDED``` might make more sense here.

2021-11-05 12:42 UTC, riversy commented on views/js/simplify.embedded.js
> +        if (response && response.length > 0 && response[0].error) {
I experimented a bit more with this callback and discovered that this callback is executed only if the library has a positive response. SimplifyCommerce doesn't trigger this callback if something goes wrong, even if the error message is shown to the end-user. So the error handling doesn't make any sense in this place. So I will remove it.

The error handling also is not presented in the official integration example - https://github.com/Mastercard-Gateway/simplify-shopping/blob/43a0c0773c3908ae90afbda1531f80f012656112/hosted-checkout.php#L189.

Please, let me know if you have some additional details about error handling in this response.

2021-11-05 12:43 UTC, riversy commented on views/js/simplify.embedded.js
> +            hostedPaymentsOnject.enablePayBtn();
I will remove this part as it does make sense only if the error handling is executed. But as per the previous thread, it doesn't seem to happen.

2021-11-05 13:00 UTC, riversy commented on views/js/simplify.embedded.js
> +            chosenPaymentOption: PAYMENT_OPTION_NEW,
I think the naming here is initially wrong as we're talking about usage saved/new card. Thank you for this mention. I will fix the naming.

2021-11-08 12:46 UTC, riversy commented on views/js/simplify.embedded.js
> +            if (state.paymentError.code === "validation") {
It seems like this error handler will never be triggered in the case of the Embedded Payment form. As we discussed for other integration modules, the current implementation is assumed to work the following way: we pass all we get to the Backend by form submission if we receive a response. And then Backend tries to submit the payment using token. If the token is not appropriate or missed, or the Gateway declines payment, the Customer will be redirected to the Shopping Cart page, and the error will be displayed.

I will remove this unnecessary code to simplify the solution.

2021-11-15 12:10 UTC, BlainMaguire commented on views/js/simplify.embedded.js
> +            if (state.paymentError.code === "validation") {
So I'm thinking of scenarios like this:
![image](https://user-images.githubusercontent.com/632629/141779034-3a40ab90-b07f-4980-86ee-17a6e3ba39ea.png)

Where a customer might try a card that is [declined](https://simplify.com/commerce/docs/testing/test-card-numbers). They should get feedback in the UI (based on the API response) in the embedded mode like the above screenshot. That would be the main thing. If we don't need JS code to handle the error response (as you point out) then it's best to remove that code.

2021-11-15 12:11 UTC, BlainMaguire commented on views/js/simplify.embedded.js
> +        if (response && response.length > 0 && response[0].error) {
I will resolve this since I think it's already covered in this comment:

https://github.com/Mastercard-Gateway/simplify-prestashop-module/pull/8#discussion_r749269254

2021-11-17 05:39 UTC, riversy commented on views/js/simplify.embedded.js
> +            if (state.paymentError.code === "validation") {
I am agreed with this position. 

I've already removed this piece of handlers because it hasn't been used, and I'm not sure why it was added. It probably did make sense in the past, but after recent modifications, it never triggered. 

The response object is assumed to be the same as it presented in the official example. It should contain the card token. And even if it doesn't, nothing should happen with the page because this is the same place on the page, so the embedded form controls itself. Later, if the customer passes correct card details again, our handler receives the token and submits it to the backend. The payment creation will happen on the backend side. As a result, if the card will be declined, we will know about it on the backend side. In this case, the backend redirects the customer back to the checkout page and with an error message. 

The styles of the error message will be a bit different from the error message you've displayed, but it can always be stylized on the theme level.

2021-11-17 10:39 UTC, BlainMaguire approved these changes

2021-11-17 11:59 UTC, merged